### ISSUE TITLE
Kickoff Mobile-web.dev

### ISSUE THREAD

**Issue by amanintech** [mobile-web-dev/Events#1]
The first meetup of Mobile-web.dev community named as kickoff meet

these are the planning tasks that  I can see so far
 

- [x] Logo
- [x] Landing Page Story 
- [x] Commudle 
- [x] Meetup
- [ ] PaperCall.io
- [ ] Event Banners 
- [ ] Social Media Templates 
- [x] Event pages 
- [x] Social media Posting 
- [ ] Swags 
- [ ] F & B 
- [x] Venue proposal
- [ ] Community Partner Proposal
- [x] Venue 
- [x] Cost Estimated 
- [ ] Sponsor Proposal 
- [ ] Sponsorship
- [ ] Campus Ambasdor programme
- [x] Mail About the event to Google and AMP 
- [x] Call for Speakers 
- [ ] Community Spread 
- [ ] Speakers and organizers badges 
- [ ] Sound and Projector 
- [ ] Recording

**Comment by amanintech** [comment]
Registrations to be created 

- [ ] Campus Ambassador programme 
- [ ]

**Comment by amanintech** [comment]
tentative speakers -
Aman sharma  ( AMP )
Aayush ( GDE ) 
Prany( GDGC)
Pawan ( GDE ) 
Vrijraj ( GDE Web )
AmanDeep
!Anuj 
Rabimba
Raghav
Saurabh Rajpal
Siddhant Aggarwal
Vipul Gupta

**Comment by amanintech** [comment]
tentative dates - 
CFP open - 7 feb 
CFP closed 14 feb 
speaker annoucments - 16 FEB 
registration opens - 17 feb 
registration closed - 3 March 
Event Date - 8 March

**Comment by amanintech** [comment]
company partnerships 
 1. Twimbit 
2. Nukleus Co-working 
3. Google
4. MS
5. Voiceflow 
6. Mozilla 
7. Jetbrains

Community partnership -
1. DSC Galgotia 
2. JIIT 
3. DSC GTBIT 
4. Amity
5. DSC Sharda 
6. GDG Delhi
7. GCDC Delhi 
8. Facebook Developer  Circles  
9. JS Lovers 
10. React NCR 
11. Angular India 
12. DSC UIT 
13. GirlScript
14. WTM 
15. BIZcom 
16. Headstart 
17. lets flutter with dart
18. DSC JSCRC
19. Wordpress 
20. TechTalks

**Comment by harshakshit** [comment]
# Venue Proposal

To,                                                                                                                       Date: 



Subject: ​Application ​for ​organising ​.

Sir/Madam,
This is a request  for our heartily wish to organise **Kickoff Mobile-web.dev**
at ​your ​venue.
Event ​Date ​: 8th March ​2020 ​( Sunday ​)

As we are calling all the developers from Delhi NCR region, this can serve as an intermediate event about Mobile and Web development technologies.

Mobile-web.dev is a group of developers that fosters learning and interaction with Mobile and Web development technologies.
We are a local community-run meetup program for developers interested in resources and
technologies. The membership is free & open to all the tech
enthusiasts and run by passionate individuals in the developer community.

We hope to have you as our venue partner, where developers can learn about the
latest Mobile-web technologies from Google Experts and world leaders. Students will get all the opportunity to participate in Hackathons from different universities, compete there, and
complete the project in a given time frame.
So, it’s a humble request to accept the proposal to organise this event.

Thanking ​you
Regards,
Aman Sharma 
Founder, Mobile-web.dev

**Comment by harshakshit** [comment]
# Community Proposal
Keeping in mind the demands of present world, and growing craze for mobile app development, we are trying to break the hype that creates a distinction between mobile and web development  among the developers. As we witness nowadays, all our phones are directly connected to internet, it is our prime duty to maintain the balance of both mobile-web sources. Hence, we are here to foster the development based on flutter, react,graphQL and many other tools which will caliberate through web and mobile both.
We are organising  a community meetup for mobile-web development based interactions around the nation starting from Delhi NCR. It will target meetups, interactions, and large scale hackathons for enthusiasts.

 As per we encounter rapid growth in android and ios development resources such as flutter, and react , we get an opportunity to quench the thirst of all the tech-enthusiasts considering themselves to learn mobile app development. 

It can justify the one of the largest community based meetup. And your support in this can lead us to a very moduled way to reach most of the technical communities around the nation. The amalgamation of communitites can be fruitful to all of us. 

Hence, it is a humble request to join and foster us  for a good cause. It can lead us to a path of self learned technical community and developement of speakers from us.

**Comment by harshakshit** [comment]
> tentative dates -
> CFP open 
> CFP closed 02 March
> speaker annoucments - 02 March
> registration opens - 24 feb
> registration closed - 08 March
> Event Date - 15 March
> Community Partners announcement - 16 Feb
