### ISSUE TITLE
31 October | WEB vs Mobile

### ISSUE THREAD

**Issue by mounicarajput** [mobile-web-dev/Events#5]
S.No | Date | Event Title | Description | Speaker Name
----------------|------------ | -------------|-------------|---------------
1  |31 October |Web vs Mobile|The rivalry between the web and the mobile in terms of interfaces, usage, experience and on lot more basis. | Riya Suntwal  https://www.linkedin.com/mwlite/in/carrisunrio https://github.com/carrisunrio https://twitter.com/suntwal_riya

Task According to high Priority 
- [x] Speaker Relation
- [x] Social Media Poster
- [x] Social Media Shout-out on all platforms 
- [x] Content (PPT )
- [ ] Event Management (Streaming)

**Comment by hashtagaps** [comment]
![Riya Suntwal](https://user-images.githubusercontent.com/44193346/96596044-ea366980-1309-11eb-8cf0-60b79c64e27f.png)

**Comment by hashtagaps** [comment]
![Riya-01](https://user-images.githubusercontent.com/44193346/96596488-64ff8480-130a-11eb-9103-2bbcf17a9a89.png)
